Feature: I want to test the homepage
    @javascript @anon
    Scenario: As an anonymous user I want to make sure that the homepage works properly
        Given I visit "/user/register"
        Then I click "Access as a Guest"
        Then I should see text matching "BETA VERSION"
        Then I should see text matching "Data"
        Then I should see text matching "Join the Exchange"
        Then I should see text matching "Log In"
        Then I should see text matching "ABOUT"
        Then I should see text matching "INNOVATIONS"
        Then I should see text matching "FUNDING"
        Then I should see text matching "RESOURCES"
        Then I should see text matching "ENGINES"
        Then I should see text matching "MORE"
        Then I should see text matching "The Exchange Connects."
        Then I should see text matching "Our tools are totally free. Start here"
        Then I should see text matching "Find your place on the Exchange"
        Then I should see text matching "The Exchange Mission"
        Then I should see the heading "HIGHLIGHTS"
        Then I should see text matching "View All Innovations"
        Then I should see text matching "ADD INNOVATION"
        Then I should see the heading "FUNDING OPPORTUNITIES"
        Then I should see text matching "View All Funding"
        Then I should see text matching "ADD FUNDING"
        Then I should see text matching "The Exchange Mission"
        Then I should see text matching "LEARN MORE"
        Then I should see text matching "Ready to get started?"
        Then I should see text matching "Members"
        Then I should see text matching "Programs"
        Then I should see text matching "Organizations"
        Then I should see text matching "Discussions"
        Then I should see text matching "FAQs"
        Then I should see text matching "Contact"

    @api @javascript @admin
    Scenario: As an administrator user I want to make sure that the homepage works properly
        Given I am logged in as a user with the "administrator" roles
        Given I am on the homepage
        Then I should see text matching "BETA VERSION"
        Then I should see text matching "Data"
        Then I should see text matching "Join the Exchange"
        Then I should see text matching "Log In"
        Then I should see text matching "ABOUT"
        Then I should see text matching "INNOVATIONS"
        Then I should see text matching "FUNDING"
        Then I should see text matching "RESOURCES"
        Then I should see text matching "ENGINES"
        Then I should see text matching "MORE"
        Then I should see text matching "The Exchange Connects."
        Then I should see text matching "Our tools are totally free. Start here"
        Then I should see text matching "Find your place on the Exchange"
        Then I should see text matching "The Exchange Mission"
        Then I should see the heading "HIGHLIGHTS"
        Then I should see text matching "View All Innovations"
        Then I should see text matching "ADD INNOVATION"
        Then I should see the heading "FUNDING OPPORTUNITIES"
        Then I should see text matching "View All Funding"
        Then I should see text matching "ADD FUNDING"
        Then I should see text matching "The Exchange Mission"
        Then I should see text matching "LEARN MORE"
        Then I should see text matching "Ready to get started?"
        Then I should see text matching "Members"
        Then I should see text matching "Programs"
        Then I should see text matching "Organizations"
        Then I should see text matching "Discussions"
        Then I should see text matching "FAQs"
        Then I should see text matching "Contact"


