Feature: I want to test the 'innovations' page
    @javascript @anon
    Scenario: As an anonymous user I want to make sure that the innovations page works properly
        Given I visit "/innovations"
        Then I should see text matching "INNOVATIONS / IDEAS"
        Then I should see text matching "ADD AN INNOVATION"
        Then I should see text matching "Filter By"
        Then I should see text matching "Assistance Sought"
        Then I should see text matching "Sectors"
        Then I should see text matching "Topics"
        Then I should see text matching "Stage of Innovation"
        Then I should see text matching "Type of Innovation"
        Then I should see text matching "Program"
        Then I should see text matching "Region"
        Then I should see text matching "Created In"
        Then I should see text matching "Implemented In"
        Then I should see text matching "Evidence Available?"
        Then I should see text matching "References Available?"
        Then I should see text matching "Organizations"
        Then I should see text matching "Funding Partners"
        Then I should see text matching "Cost Per Unit"
        Then I should see text matching "Funding Raised"
        Then I should see text matching "Funding Goal"

    @api @javascript @admin
    Scenario: As an administrator user I want to make sure that the innovations page works properly
        Given I am logged in as a user with the "administrator" roles
        Given I visit "/innovations"
        Then I should see text matching "INNOVATIONS / IDEAS"
        Then I should see text matching "ADD AN INNOVATION"
        Then I should see text matching "Filter By"
        Then I should see text matching "Assistance Sought"
        Then I should see text matching "Sectors"
        Then I should see text matching "Topics"
        Then I should see text matching "Stage of Innovation"
        Then I should see text matching "Type of Innovation"
        Then I should see text matching "Program"
        Then I should see text matching "Region"
        Then I should see text matching "Created In"
        Then I should see text matching "Implemented In"
        Then I should see text matching "Evidence Available?"
        Then I should see text matching "References Available?"
        Then I should see text matching "Organizations"
        Then I should see text matching "Funding Partners"
        Then I should see text matching "Cost Per Unit"
        Then I should see text matching "Funding Raised"
        Then I should see text matching "Funding Goal"
