Feature: I want to test the 'sectors' page
    @javascript @anon
    Scenario: As an anonymous user I want to make sure that the sectors page works properly
        Given I visit "/sectors"
        Then I should see text matching "SECTORS"
        Then I should see text matching "REQUEST A SECTOR"
        Then I should see text matching "Agriculture"
        Then I should see text matching "Democracy, Human Rights, and Governance"
        Then I should see text matching "Digital Development & Enabling Technologies"
        Then I should see text matching "Economic Growth and Trade"
        Then I should see text matching "Education"
        Then I should see text matching "Energy"
        Then I should see text matching "Environment"
        Then I should see text matching "Gender"
        Then I should see text matching "Health"
        Then I should see text matching "Housing and Infrastructure"
        Then I should see text matching "Humanitarian Assistance"
        Then I should see text matching "Lesbian, Gay Bisexual, and Transgender"
        Then I should see text matching "(LGBT)"
        Then I should see text matching "Other"
        Then I should see text matching "Transport & Supply Chain"
        Then I should see text matching "(WASH)"
        Then I should see text matching "Water Sanitation and Hygiene"
        Then I should see text matching "Youth"

    @api @javascript @admin
    Scenario: As an administrator user I want to make sure that the resource page works properly
        Given I am logged in as a user with the "administrator" roles
        Given I visit "/sectors"
        Then I should see text matching "SECTORS"
        Then I should see text matching "REQUEST A SECTOR"
        Then I should see text matching "Agriculture"
        Then I should see text matching "Democracy, Human Rights, and Governance"
        Then I should see text matching "Digital Development & Enabling Technologies"
        Then I should see text matching "Economic Growth and Trade"
        Then I should see text matching "Education"
        Then I should see text matching "Energy"
        Then I should see text matching "Environment"
        Then I should see text matching "Gender"
        Then I should see text matching "Health"
        Then I should see text matching "Housing and Infrastructure"
        Then I should see text matching "Humanitarian Assistance"
        Then I should see text matching "Lesbian, Gay Bisexual, and Transgender"
        Then I should see text matching "(LGBT)"
        Then I should see text matching "Other"
        Then I should see text matching "Transport & Supply Chain"
        Then I should see text matching "(WASH)"
        Then I should see text matching "Water Sanitation and Hygiene"
        Then I should see text matching "Youth"