Feature: I want to test the 'topics' page
    @javascript @anon
    Scenario: As an anonymous user I want to make sure that the topics page works properly
        Given I visit "/topics"
        Then I should see text matching "TOPICS"
        Then I should see text matching "REQUEST A TOPIC"
        Then I should see text matching "Acceleration"
        Then I should see text matching "Adolescent Girls' Education"
        Then I should see text matching "Communications and Media"
        Then I should see text matching "Data for Development"
        Then I should see text matching "Diaspora"
        Then I should see text matching "Digital Development"
        Then I should see text matching "Digital Finance"
        Then I should see text matching "Digital Inclusion & Connectivity"
        Then I should see text matching "Digital Security"
        Then I should see text matching "Ebola"
        Then I should see text matching "Engineering"
        Then I should see text matching "Evaluation and Impact of Development Innovation"
        Then I should see text matching "Evidence of Impact"
        Then I should see text matching "Gamification"
        Then I should see text matching "Gender-based Violence"
        Then I should see text matching "GIS/ Development Mapping"
        Then I should see text matching "Green Chemistry"
        Then I should see text matching "Human Centered Design"
        Then I should see text matching "Intellectual Property and the Law"
        Then I should see text matching "Let Girls Learn"
        Then I should see text matching "Makers Space / Tech Spot"
        Then I should see text matching "Open-Source/Ideation Crowdsourcing Solvers"
        Then I should see text matching "Peace Building"
        Then I should see text matching "Public-Private Partnerships"
        Then I should see text matching "Research"
        Then I should see text matching "Resilience"
        Then I should see text matching "Scale"
        Then I should see text matching "Social and Behavior Change"
        Then I should see text matching "Social Impact Investing"
        Then I should see text matching "Supply Chain"
        Then I should see text matching "Systems Change"
        Then I should see text matching "Talent Management"
        Then I should see text matching "Unmanned Aerial Vehicles"
        Then I should see text matching "(UAVs)"
        Then I should see text matching "Venture Capital"

    @api @javascript @admin
    Scenario: As an administrator user I want to make sure that the resource page works properly
        Given I am logged in as a user with the "administrator" roles
        Given I visit "/topics"
        Then I should see text matching "TOPICS"
        Then I should see text matching "REQUEST A TOPIC"
        Then I should see text matching "Acceleration"
        Then I should see text matching "Adolescent Girls' Education"
        Then I should see text matching "Communications and Media"
        Then I should see text matching "Data for Development"
        Then I should see text matching "Diaspora"
        Then I should see text matching "Digital Development"
        Then I should see text matching "Digital Finance"
        Then I should see text matching "Digital Inclusion & Connectivity"
        Then I should see text matching "Digital Security"
        Then I should see text matching "Ebola"
        Then I should see text matching "Engineering"
        Then I should see text matching "Evaluation and Impact of Development Innovation"
        Then I should see text matching "Evidence of Impact"
        Then I should see text matching "Gamification"
        Then I should see text matching "Gender-based Violence"
        Then I should see text matching "GIS/ Development Mapping"
        Then I should see text matching "Green Chemistry"
        Then I should see text matching "Human Centered Design"
        Then I should see text matching "Intellectual Property and the Law"
        Then I should see text matching "Let Girls Learn"
        Then I should see text matching "Makers Space / Tech Spot"
        Then I should see text matching "Open-Source/Ideation Crowdsourcing Solvers"
        Then I should see text matching "Peace Building"
        Then I should see text matching "Public-Private Partnerships"
        Then I should see text matching "Research"
        Then I should see text matching "Resilience"
        Then I should see text matching "Scale"
        Then I should see text matching "Social and Behavior Change"
        Then I should see text matching "Social Impact Investing"
        Then I should see text matching "Supply Chain"
        Then I should see text matching "Systems Change"
        Then I should see text matching "Talent Management"
        Then I should see text matching "Unmanned Aerial Vehicles"
        Then I should see text matching "(UAVs)"
        Then I should see text matching "Venture Capital"